# If we configure the azure.activedirectory.client-id or azure.activedirectory.app-id-uri will be to check the audience.
# In v2.0 tokens, this is always the client ID of the API, while in v1.0 tokens it can be the client ID or the resource URI used in the request.
# If you are using v1.0 tokens, configure both to properly complete the audience validation.

server:
  port: 8082

azure:
 activedirectory:
   client-id: db369e8a-637c-45c8-af70-3e0949e9402e
   app-id-uri: api://db369e8a-637c-45c8-af70-3e0949e9402e